name: sw_air_link
description: SW Air Link mobile bridge app.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
